friend_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('friend_app/', include('friend_app.urls'))
]

friend_app/urls.py
from django.urls import path
from . import views

app_name = 'friend_app'

urlpatterns = [
    path('', views.user_list, name='list'),
    path('<int:friendly_user_id>/', views.user_retrieve, name='retrieve'),
    path('<int:user_id_1>/start_friendship/', views.start_friendship, name='start_friendship'),
    path('<int:user_id_1>/end_friendship/', views.end_friendship, name='end_friendship'),
]

friend_app/models.py
from django.db import models as models


class FriendError(Exception):
    def __init__(self, message):
        self.message = message


class FriendlyUser(models.Model):
    username = models.CharField('username', max_length=20)

    def __str__(self):
        return self.username


class Friendship(models.Model):
    date = models.DateTimeField()
    friend1 = models.ForeignKey(FriendlyUser, on_delete=models.CASCADE, related_name='friend1')
    friend2 = models.ForeignKey(FriendlyUser, on_delete=models.CASCADE, related_name='friend2')

    def __str__(self):
        return str(self.friend1) + ' and ' + str(self.friend2)

friend_app/views.py
from django.shortcuts import render
from .models import FriendlyUser, Friendship
from django.http import Http404, HttpResponseRedirect, HttpResponseBadRequest
from operator import attrgetter
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q


def get_friends(user):
    def get_f1(friendship):
        return friendship.friend1

    def get_f2(friendship):
        return friendship.friend2

    return list(map(get_f2, user.friend1.all())) + list(map(get_f1, user.friend2.all()))


def user_list(request):
    users = FriendlyUser.objects.order_by('username')
    return render(request, 'friend_app/list.html', {'users': users})


def user_retrieve(request, friendly_user_id):
    try:
        u = FriendlyUser.objects.get(id=friendly_user_id)
    except:
        raise Http404('Page not found')

    friends = sorted(get_friends(u), key=attrgetter('username'))

    return render(request, 'friend_app/retrieve.html', {'user': u, 'friends': friends})


def start_friendship(request, user_id_1):
    user_id_2 = request.POST["friend_id"]
    try:
        u1 = FriendlyUser.objects.get(id=user_id_1)
        u2 = FriendlyUser.objects.get(id=user_id_2)
    except:
        return HttpResponseBadRequest('User not in database')

    if u2 == u1:
        return HttpResponseBadRequest('Friendship requires two distinct users')

    if u1 not in get_friends(u2):
        date = timezone.now()
        Friendship(friend1=u1, friend2=u2, date=date).save()

    return HttpResponseRedirect(reverse('friend_app:retrieve', args=(user_id_1,)))


def end_friendship(request, user_id_1):
    user_id_2 = request.POST["friend_id"]
    try:
        u1 = FriendlyUser.objects.get(id=user_id_1)
        u2 = FriendlyUser.objects.get(id=user_id_2)
    except:
        return HttpResponseBadRequest('User not in database')

    if u1 in get_friends(u2):
        Friendship.objects.get(Q(friend1=u1, friend2=u2) | Q(friend1=u2, friend2=u1)).delete()

    return HttpResponseRedirect(reverse('friend_app:retrieve', args=(user_id_1,)))

friend_api/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}My site{% endblock %}</title>
</head>
<body>

	{% block content %}{% endblock %}

</body>
</html>

friend_api/templates/friend_app/list.html
{% extends 'base.html' %}
{% block title %}List of users{% endblock %}
{% block content %}

	{% if users %}
		{% for u in users %}
			<a href="{% url 'friend_app:retrieve' u.id %}">{{u.username}}</a> <br>
		{% endfor %}
	{% endif %}

{% endblock %}

friend_api/templates/friend_app/retrieve.html
{% extends 'base.html' %}
{% block title %}{{user.username}}{% endblock %}
{% block content %}

    <h2>{{user.username}}</h2>

    <hr>

    {% if friends %}
        {% for u in friends %}
			<a href="{% url 'friend_app:retrieve' u.id %}">{{u.username}}</a>

            <form action="{% url 'friend_app:end_friendship' user.id %}" method="POST">

                {% csrf_token %}

                <button type="submit" name="friend_id" value="{{u.id}}">End friendship</button>

            </form>

            <br>
		{% endfor %}
	{% endif %}

    <hr>

    <form action="{% url 'friend_app:start_friendship' user.id %}" method="POST">

        {% csrf_token %}

        <input type="number" required placeholder="New friend id" name="friend_id"><br>
        <button type="submit">Add new friend</button>
    </form>

{% endblock %}